export enum ToolKeys {
    Pencil = 'c',
    Aerosol = 'a',
    Rectangle = '1',
    Ellipse = '2',
    Polygon = '3',
    Line = 'l',
    Text = 't',
    Bucket = 'b',
    Eraser = 'e',
    Stamp = 'd',
    Pipette = 'i',
    SelectionRectangle = 'r',
    SelectionEllipse = 's',
    Lasso = 'v',
    Grid = 'g',
    Magnetism = 'm',
}
